# See https://github.com/actions/dependency-review-action for more information

name: Dependency Review

# Trigger the workflow on every pull request
on:
  pull_request:

# Set permissions to read-only for contents to enhance security
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Step names are arbitrary and will appear in the GitHub actions UI
    - name: Perform dependency review
      uses: actions/dependency-review-action@v4
      with:
        retry-on-snapshot-warnings: true
        retry-on-snapshot-warnings-timeout: 600
